FROM alpine:latest

# Install dependencies
RUN apk add --no-cache \
    g++ \
    cmake \
    make \
    linux-headers \
    iproute2 \
    net-tools \
    tcpdump

# Copy project files
COPY . /app
WORKDIR /app

# Build the project
RUN mkdir -p build-test && \
    cd build-test && \
    cmake .. -DCMAKE_BUILD_TYPE=Debug -DProject_ENABLE_UNIT_TESTING=ON -DProject_USE_GTEST=ON && \
    cmake --build .

# Default command
CMD ["/bin/sh"]

